# Generated by Django 4.2.7 on 2023-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.CharField(default='9:00', verbose_name='время рассылки')),
                ('periodicity_newsletter', models.CharField(default='0 0 0 * *', verbose_name='переодичность')),
                ('status_newsletter', models.CharField(default='создана', verbose_name='статус')),
            ],
            options={
                'verbose_name': 'рассылка (настройки)',
                'verbose_name_plural': 'рассылки (настройки)',
            },
        ),
        migrations.CreateModel(
            name='MassageMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_letter', models.CharField(max_length=150, verbose_name='Тема')),
                ('body_letter', models.TextField(verbose_name='тело')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254, verbose_name='email')),
                ('client_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('client_comment', models.TextField(verbose_name='коментарий')),
                ('mailing', models.ManyToManyField(to='newsletter.mailing')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
