# Generated by Django 4.2.7 on 2023-12-10 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_last_try', models.DateTimeField(auto_now=True)),
                ('status_log', models.BooleanField(verbose_name='статус отправки рассылки')),
                ('server_response', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MassageMailing',
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_active', 'Can active mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='serviceclient',
            options={'permissions': [('set_active_client', 'Can active client')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='mailing_time',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='periodicity_newsletter',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='status_newsletter',
        ),
        migrations.RemoveField(
            model_name='serviceclient',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='body_letter',
            field=models.TextField(blank=True, null=True, verbose_name='Текс рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='newsletter.serviceclient'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Еженедельная'), ('monthly', 'Ежемесячная')], default='weekly', max_length=20, verbose_name='Периодичность рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запушена'), ('done', 'Завершена')], default='created', max_length=20, verbose_name='Статус рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='subject_letter',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тема рассылки'),
        ),
        migrations.AddField(
            model_name='serviceclient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceclient',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='serviceclient',
            name='client_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.serviceclient', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.mailing', verbose_name='рассылка'),
        ),
    ]
