# Generated by Django 4.2.7 on 2023-11-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_log', models.BooleanField(verbose_name='статус отправки рассылки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.serviceclient', verbose_name='клиент')),
            ],
        ),
        migrations.DeleteModel(
            name='MassageMailing',
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='mailing_time',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='periodicity_newsletter',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='status_newsletter',
        ),
        migrations.AddField(
            model_name='mailing',
            name='body_letter',
            field=models.TextField(blank=True, null=True, verbose_name='тело'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Еженедельная'), ('monthly', 'Ежемесячная')], default='weekly', max_length=20, verbose_name='Периодичность рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запушена'), ('done', 'Завершена')], default='created', max_length=20, verbose_name='Статус рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='subject_letter',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.mailing', verbose_name='рассылка'),
        ),
    ]
