# Generated by Django 4.2.7 on 2023-11-27 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_mailinglog_delete_massagemailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='time_last_try',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='body_letter',
            field=models.TextField(blank=True, null=True, verbose_name='Текс рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='subject_letter',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тема рассылки'),
        ),
        migrations.AlterField(
            model_name='serviceclient',
            name='client_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
