# Generated by Django 4.2.7 on 2023-12-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_mailinglog_delete_massagemailing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='client',
            new_name='clients',
        ),
    ]
