# Generated by Django 4.2.7 on 2023-11-27 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_mailing_start_time_mailinglog_time_last_try_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
