# Generated by Django 4.2.7 on 2023-11-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_mailing_end_time_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='server_response',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
