# Generated by Django 4.2.7 on 2023-12-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_alter_mailinglog_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
