# Generated by Django 4.2.7 on 2023-12-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_alter_serviceclient_options_serviceclient_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceclient',
            options={'permissions': [('set_active_client', 'Can active client')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
    ]
